In [1]:
import numpy
    



In [10]:
a=numpy.array([1,2,3,4,5,6,7,8])

In [6]:
b=numpy.array([3,4,5])

In [8]:
a+b

array([4, 6, 8])

In [9]:
a


array([1, 2, 3])

In [11]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
a=numpy.reshape([4,4])

TypeError: _reshape_dispatcher() missing 1 required positional argument: 'newshape'

In [15]:
numpy.pad(a,(1,1))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0])

In [21]:
p=numpy.array([[1,2,3],[3,4,5]])

In [22]:
p

array([[1, 2, 3],
       [3, 4, 5]])

In [23]:
q=numpy.array([[2,3,4],[4,5,6]])

In [24]:
p+q

array([[ 3,  5,  7],
       [ 7,  9, 11]])

In [25]:
p*q

array([[ 2,  6, 12],
       [12, 20, 30]])

In [ ]:
def fib(n):
    if n == 1:
        return 1
    elif n == 2:
        return 1
    return (fib(n-1) + fib(n-2))
p=50
f=fib(p)
print(f)



In [ ]:
a = [10, 20, 30]

b = [40, 50, 60]

print(a)
print(b)

c = a + b

print(c[::-1])